export const users = [
  {
    id: 1,
    img:"https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
    specilist:"Dentist",
    firstName: "Dr. Alice",
    qualification:"BDS",
    helpline_number: "+91 95 9090 8080",
       },
  {
    id:2,
    img:"https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
    specilist:"cardiologist",
    firstName: "Assia",
    qualification:"Cardiology",
    helpline_number: "+91 95 9090 8080",
  },
  {
    id: 3,
    img:"https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
    specilist:"General Surgeon",
    firstName: "Abas",
    qualification:"MBBS, MCh Paediatric surgery",
    helpline_number: "+91 95 9090 8080",
  },
  {
    id: 4,
    img:"https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
    specilist:"SURGICAL GASTRO",
    firstName: "Mimisha",
    qualification:"MBBS",
    helpline_number: "+91 95 9090 8080",
  },
  {
    id: 5,
    img:"https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
    specilist:"Pediatrician",
    firstName: "test1",
    qualification:"BDS",
    helpline_number: "+91 95 9090 8080",
    },
    {
      id:6,
      img:"https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
      specilist:"Neurologist",
      firstName: "dr.sumit chaudhary",
      qualification:"M.Ch",
      helpline_number: "+91 95 9090 8080",
      },
      {
        id: 7,
        img:"https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
        specilist:"Dentist",
        firstName: "Dr. Alice",
        qualification:"BDS",
        helpline_number: "+91 95 9090 8080",
           },
      {
        id: 8,
        img:"https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
        specilist:"ardiologist",
        firstName: "Assia",
        qualification:"Cardiology",
        helpline_number: "+91 95 9090 8080",
      },
      {
        id: 9,
        img:"https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
        specilist:"General Surgeon",
        firstName: "Abas",
        qualification:"MBBS,MCh Paediatric surgery",
        helpline_number: "+91 95 9090 8080",
      },
      {
        id: 10,
        img:"https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
        specilist:"SURGICAL GASTRO",
        firstName: "Mimisha",
        qualification:"MBBS",
        helpline_number: "+91 95 9090 8080",
      },
      {
        id: 11,
        img:"https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
        specilist:"Pediatrician",
        firstName: "test1",
        qualification:"BDS",
        helpline_number: "+91 95 9090 8080",
        },
        {
          id: 12,
          img:"https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
          specilist:"Neurologist",
          firstName: "test2",
          qualification:"M.Ch",
          street_address: "1234/56, 9th Cross", 
          street_address1 :"J P Nagar 3 Phase",
          helpline_number: "+91 95 9090 8080",
          }, 
          {
            id: 13,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "Neurologist",
            firstName: "Dr Vineet Saggar",
            qualification: "MBBS,BDA,M.ch",
            helpline_number: "+98724 23999",
          },
          {
            id: 14,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "Neurologist",
            firstName: "Dr Jaslovleen Sidhu",
            qualification: "MBBS,BDA,M.ch",
            helpline_number: "+98724 23999",
          },
          {
            id: 15,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "Neurologist",
            firstName: "Dr Amandeep Singh ",
            qualification: "MBBS,BDA,M.ch",
            helpline_number: "+98724 23999",
          },
          {
            id: 16,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "Neurologist",
            firstName: "Dr Rajeev Garg ",
            qualification: "MBBS,BDA,M.ch",
            helpline_number: "+91 98 5623 4102",
          },
          {
            id: 17,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "Neurologist",
            firstName: "Dr Neha Aggarwal ",
            qualification: "MBBS,BDA,M.ch",
            helpline_number: "+91 98 5623 4102",
          },
          {
            id: 18,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "Neurologist",
            firstName: "Dr Nitish Arora",
            qualification: "MBBS,BDA,M.ch",
            helpline_number: "+91 98 5623 4102",
          },
          {
            id: 19,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "Neurologist",
            firstName: "Dr Samir khan",
            qualification: "MBBS,M.ch",
            helpline_number: "+91 98 0223 4102",
          },
          {
            id: 20,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "Neurologist",
            firstName: "Dr Sumeet Singh",
            qualification: "MBBS",
            helpline_number: "+91 98 0223 5202",
          },
          {
            id: 21,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "Neurologist",
            firstName: "Dr Rajeev Goel",
            qualification: "MBBS",
            helpline_number: "+91 98 0289 2899",
          },
          {
            id: 22,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "Neurologist",
            firstName: "Dr Deepak Gupta ",
            qualification: "MBBS,BDEE",
            helpline_number: "+91 98 0255 5561",
          },
          {
            id: 23,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "Neurologist",
            firstName: "Dr Jaspreet Singh Randhawa  ",
            qualification: "MBBS,BDEE",
            helpline_number: "+91 98 0855 5861",
          },
          {
            id: 24,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "Neurologist",
            firstName: "Dr. Nitti Kapoor Kaushal",
            qualification: ": MBBS, MD, DM",
            helpline_number: "+91 95  1363 1594",
          },
          {
            id: 25,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "Neurologist",
            firstName: "Dr. Satwant Singh Sachdeva",
            qualification: " MBBS, MS, MCh",
            helpline_number: "+91 98 0855 5861",
          },
          {
            id: 26,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "Neurologist",
            firstName: "Dr.Louis Chang",
            qualification: "M.D",
            helpline_number: "+91 98 2341 5860",
          },
          {
            id: 15  ,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "Neurologist",
            firstName: "Dr.Youssef G Comair,",
            qualification: "M.D,Ph.D",
            helpline_number: "+91 98 2341 5860",
          },
          {
            id: 27 ,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "Neurologist",
            firstName: "Dr.Shih-Chun Lin",
            qualification: "Ph.D",
            helpline_number: "+91 98 2341 5860",
          },
          {
            id: 27,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "Neurologist",
            firstName: "Dr Sushil Kumar Rahi",
            qualification: "Ph.D",
            helpline_number: "+91 98 2562 5260",
          },
          {
            id: 28,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "Neurologist",
            firstName: "Dr. Sumeet Singh",
            qualification: "Ph.D,M.s,M.D",
            helpline_number: "+91 98 2562 5260",
          },
          {
            id: 29,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "Otolaryngologists",
            firstName: "Dr Rajvinder ",
            qualification: "MBBS,BDA,M.ch",
            helpline_number: "+91 99885 39699",
          },
          {
            id: 30,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "Otolaryngologists",
            firstName: "Dr.Leslie L. Baker ",
            qualification: "MBBS,MD,M.ch",
            helpline_number: "+91 99025 39699",
          },
          {
            id: 31,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "Otolaryngologists",
            firstName: "Dr.Stewart H. Bernard ",
            qualification: "MBBS,MD",
            helpline_number: "+91 99025 39699",
          },
          {
            id: 32,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "Otolaryngologists",
            firstName: "Dr.Elise C. Denneny",
            qualification: "MD, FACS",
            helpline_number: "+91 99025 39699",
          },
          {
            id: 33,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "Otolaryngologists",
            firstName: "Dr.Richard J. DePersio",
            qualification: "MD, FACS",
            helpline_number: "+91 99056 39239",
          },
          {
            id: 34,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "Otolaryngologists",
            firstName: "Dr.Quinn A. Dunlap",
            qualification: "MD",
            helpline_number: "+91 99016 56239",
          },
          {
            id: 35,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "Otolaryngologists",
            firstName: "Dr.William D. Horton",
            qualification: "MD, FACS  ",
            helpline_number: "+91 99016 56239",
          },
          {
            id: 36,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "Otolaryngologists",
            firstName: "Dr.Christopher J. Rathfoot",
            qualification: "MD ",
            helpline_number: "+91 9962 124539",
          },
          {
            id: 37,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "Otolaryngologists",
            firstName: "Dr.Allan M. Rosenbaum",
            qualification: "MD ",
            helpline_number: "+91 9962 562339",
          },
          {
            id: 38,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "Otolaryngologists",
            firstName: "Dr.Joseph White",
            qualification: "MD ",
            helpline_number: "+91 99621 21039",
          },
          {
            id: 39,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "ENT",
            firstName: "Dr.Sarah A. Harvey",
            qualification: "FNP-BC, CORLN ",
            helpline_number: "+91 99621 21039",
          },
          {
            id: 40,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "ENT",
            firstName: "Dr.Lauren L. Clear",
            qualification: "PA-C",
            helpline_number: "+91 99201 21024",
          },
          {
            id: 41,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "ENT",
            firstName: "Dr.Anna Halberstadt",
            qualification: "NP",
            helpline_number: "+91 99231 21301",
          },
          {
            id: 42,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "ENT",
            firstName: "Dr.Carrie Daniels",
            qualification: "NP",
            helpline_number: "574-264-9653",
          },
          {
            id: 43,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "ENT",
            firstName: "Dr.Cynthia Pascual",
            qualification: "MD",
            helpline_number: "264-663-8288",
          },
          {
            id: 44,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "ENT",
            firstName: "Dr.Daniel Edquist",
            qualification: "MD",
            helpline_number: "219-324-1700",
          },
          {
            id: 45,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "Dermatologist",
            firstName: "Dr. Mary-margaret B. Noland",
            qualification: "MD",
            helpline_number: "219-324-1700",
          },
          {
            id: 46,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "Dermatologist",
            firstName: "Dr. Barrett J. Zlotoff",
            qualification: "MD,Ph.D",
            helpline_number: "219-324-1700",
          },
          {
            id: 47,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "Dermatologist",
            firstName: "Dr. Amy J. Mcmichael",
            qualification: "Ph.D",
            helpline_number: "220-325-1721",
          },
          {
            id: 48,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "Dermatologist",
            firstName: "Dr. Steven Q. Wang",
            qualification: "Ph.D,MD,Ph.D",
            helpline_number: "220-120-5623",
          },
          {
            id: 49,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "Dermatologist",
            firstName: "Dr. Atif U. Ahmed",
            qualification: "Ph.D,MD",
            helpline_number: "220-120-5412",
          },
          {
            id: 50,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "Dermatologist",
            firstName: "Dr. Lindsay C. Strowd",
            qualification: "Ph.D,MD",
            helpline_number: "220-120-5412",
          },
          {
            id: 51,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "Dermatologist",
            firstName: "Dr. Jennifer G. Powers",
            qualification: "Ph.D,MD",
            helpline_number: "220-451-4560",
          },
          {
            id: 52,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "Dermatologist",
            firstName: "Dr. Badri G. Modi",
            qualification: "MD",
            helpline_number: "210-521-4550",
          },
          {
            id: 53,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "Dermatologist",
            firstName: "Dr. Kord S. Honda",
            qualification: "MD",
            helpline_number: "210-213-4210",
          },
          {
            id: 54,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "Dermatologist",
            firstName: "Dr. Eden L. Lake",
            qualification: "MD,Ph.D",
            helpline_number: "212-245-4288",
          },
          {
            id: 55,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "Dermatologist",
            firstName: "Dr. Meenal K. Kheterpal",
            qualification: "MD",
            helpline_number: "212-521-4201",
          },
          {
            id: 56,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "Dermatologist",
            firstName: "Dr. Nishit S. Patel",
            qualification: "MD,Ph.D",
            helpline_number: "212-521-4101",
          },
          {
            id: 57,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "Dermatologist",
            firstName: "Dr. Farah R. Abdulla",
            qualification: "Ph.D",
            helpline_number: "221-201-4221",
          },
          {
            id: 58,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "Dermatologist",
            firstName: "Dr. Abhishek N. Aphale",
            qualification: "Ph.D,MD",
            helpline_number: "221-201-4221",
          },
          {
            id: 59,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "Dermatologist",
            firstName: "Dr. Katina C. Venetos",
            qualification: "Ph.D,MD",
            helpline_number: "221-201-4221",
          },
          {
            id: 60,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "Dermatologist",
            firstName: "Dr. Suman Kumar",
            qualification: "Ph.D,MD",
            helpline_number: "221-201-4221",
          },
          {
            id: 61,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "cardiologist",
            firstName: "Dr. Philip J. Patel",
            qualification: "MD,Ph.D,MBBS",
            helpline_number: "521-201-2314",
          },
          {
            id: 62,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "cardiologist",
            firstName: "Dr. Puneet K. Khanna",
            qualification: "MD,MBBS",
            helpline_number: "+91 98561 63521",
          },
          {
            id: 63,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "cardiologist",
            firstName: "Dr. Eric M. Sontz",
            qualification: "MBBS",
            helpline_number: "521-240-2301",
          },
          {
            id: 64,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "cardiologist",
            firstName: "Dr. Melvin A. Gonzalez",
            qualification: "MBBS,MD",
            helpline_number: "221-230-2541",
          },
          {
            id: 65,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "cardiologist",
            firstName: "Dr.David P. Choe",
            qualification: "MBBS,Ph.D",
            helpline_number: "221-541-2631",
          },
          {
            id: 66,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "cardiologist",
            firstName: "Dr. Ramon N. Torres",
            qualification: "MBBS,Ph.D",
            helpline_number: "+91 98674 45786",
          },
          {
            id: 67,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "cardiologist",
            firstName: "Dr. Joshua Kerstein",
            qualification: "MBBS,MD",
            helpline_number: "+91 98674 45786",
          },
          {
            id: 68,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "cardiologist",
            firstName: "Dr. James M. Fitts",
            qualification: "MD",
            helpline_number: "+91 98120 45214",
          },
          {
            id: 69,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "cardiologist",
            firstName: "Dr. Paul A. Tamburro",
            qualification: "MD,Ph.D",
            helpline_number: "+91 98140 56410",
          },
          {
            id: 70,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "cardiologist",
            firstName: "Dr. David G. Jones",
            qualification: "MD,Ph.D,MBBS",
            helpline_number: "112-554-8541",
          },
          {
            id: 71,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "cardiologist",
            firstName: "Dr. David G. Jones",
            qualification: "MD,Ph.D,MBBS",
            helpline_number: "112-554-8541",
          },
          {
            id: 72,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "cardiologist",
            firstName: "Dr. Gerald M. Hollander",
            qualification: "MD,Ph.D,MBBS",
            helpline_number: "112-554-8541",
          },
          {
            id: 73,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "cardiologist",
            firstName: "Dr. Damon E. Kelsay",
            qualification: "MD,Ph.D,MBBS",
            helpline_number: "112-554-8541",
          },
          {
            id: 74,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "cardiologist",
            firstName: "Dr. Robert M. Kinn",
            qualification: "MD,Ph.D,MBBS",
            helpline_number: "112-554-8541",
          },  {
            id: 75,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "cardiologist",
            firstName: "Dr. Peter Pitonak",
            qualification: "MD,Ph.D,MBBS",
            helpline_number: "112-554-8541",
          },
          {
            id: 76,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "cardiologist",
            firstName: "Dr. Michael D. Barron",
            qualification: "MD,Ph.D,MBBS",
            helpline_number: "112-554-8541",
          },
          {
            id: 77,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "cardiologist",
            firstName: "Dr. Katie M. Twomley",
            qualification: "MD,Ph.D,MBBS",
            helpline_number: "112-554-8541",
          },
          {
            id: 78,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "orthopedic",
            firstName: "Mohammed Amir",
            qualification: "MD,Ph.D,MBBS",
            helpline_number: "+91 98675 78654",
          },
          {
            id: 79,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "orthopedic",
            firstName: "Dr Gaurav Saini",
            qualification: "MD,MBBS",
            helpline_number: "+91 89561 12480",
          },
          {
            id: 80,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "orthopedic",
            firstName: "Dr. Manuj Wadhwa",
            qualification: "MBBS",
            helpline_number: "521-240-2301",
          },
          {
            id: 81,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "orthopedic",
            firstName: "Dr.Ajay Bhambri",
            qualification: "MBBS,MD",
            helpline_number: "221-230-2541",
          },
          {
            id: 82,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "orthopedic",
            firstName: "Dr Jagandeep S. Virk",
            qualification: "MBBS,Ph.D",
            helpline_number: "221-541-2631",
          },
          {
            id: 83,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "orthopedic",
            firstName: "Dr. Ravinder Puri",
            qualification: "MBBS,Ph.D",
            helpline_number: "+91 98674 45786",
          },
          {
            id: 84,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "orthopedic",
            firstName: "Dr Ankur Dogra",
            qualification: "MBBS,MD",
            helpline_number: "+91 98674 45786",
          },
          {
            id: 85,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "orthopedic",
            firstName: "Dr. James M. Fitts",
            qualification: "MD",
            helpline_number: "+91 98120 45214",
          },
          {
            id: 86,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "orthopedic",
            firstName: "Dr. Paul A. Tamburro",
            qualification: "MD,Ph.D",
            helpline_number: "+91 98140 56410",
          },
          {
            id: 87,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "orthopedic",
            firstName: "Dr.Jagandeep S. Virk",
            qualification: "MD,Ph.D,MBBS",
            helpline_number: "112-554-8541",
          },
          {
            id: 88,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "orthopedic",
            firstName: "Dr. Manu Mengi",
            qualification: "MD,Ph.D,MBBS",
            helpline_number: "112-554-8541",
          },
          {
            id: 89,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "orthopedic",
            firstName: "Dr.Nishant Setia",
            qualification: "MD,Ph.D,MBBS",
            helpline_number: "112-554-8541",
          },
          {
            id: 90,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "orthopedic",
            firstName: "Dr. Damon E. Kelsay",
            qualification: "MD,Ph.D,MBBS",
            helpline_number: "112-554-8541",
          },
          {
            id: 91,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "orthopedic",
            firstName: "Dr. Robert M. Kinn",
            qualification: "MD,Ph.D,MBBS",
            helpline_number: "112-554-8541",
          },  {
            id: 92,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "orthopedic",
            firstName: "Dr.Umang Verma",
            qualification: "MD,Ph.D,MBBS",
            helpline_number: "112-554-8541",
          },
          {
            id: 93,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "orthopedic",
            firstName: "Dr. Michael D. Barron",
            qualification: "MD,Ph.D,MBBS",
            helpline_number: "112-554-8541",
          },
          {
            id: 94,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "orthopedic",
            firstName: "Dr.Rajinder Sharma",
            qualification: "MD,Ph.D,MBBS",
            helpline_number: "112-554-8541",
          }, 
          {
            id: 95,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "Psychiatrist",
            firstName: "Dr.Harminder Sharma",
            qualification: "MD,Ph.D,MBBS",
            helpline_number: "112-554-8541",
          },
          {
            id: 96,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "Psychiatrist",
            firstName: "Dr.rakesh asthana",
            qualification: "MD,Ph.D,MBBS",
            helpline_number: "112-554-8541",
          },
          {
            id: 97,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "Psychiatrist",
            firstName: "Dr.Harminder Sharma",
            qualification: "MBBS",
            helpline_number: "112-554-8541",
          },
          {
            id: 98,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "Psychiatrist",
            firstName: "Dr.sheetal sharma",
            qualification: "Ph.D",
            helpline_number: "112-554-8541",
          },  {
            id: 99,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "Psychiatrist",
            firstName: "Dr.anishka thakral",
            qualification: "MD,Ph.D,MBBS",
            helpline_number: "112-554-8541",
          },
          {
            id: 100,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "Psychiatrist",
            firstName: "Dr.shyam singh",
            qualification: "MD,Ph.D,MBBS",
            helpline_number: "112-554-8541",
          },
          {
            id: 101,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "Psychiatrist",
            firstName: "Dr.pradeep yadhuvanshi",
            qualification: "MD,Ph.D,MBBS",
            helpline_number: "112-554-8541",
          }, 
          {
            id: 102,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "Psychiatrist",
            firstName: "Dr.Harminder Sharma",
            qualification: "MD,Ph.D,MBBS",
            helpline_number: "112-554-8541",
          },
          {
            id: 103,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "Psychiatrist",
            firstName: "Dr.rakesh asthana",
            qualification: "MD,Ph.D,MBBS",
            helpline_number: "112-554-8541",
          },
          {
            id: 104,
            img: "https://img.freepik.com/free-vector/doctors-concept-illustration_114360-1515.jpg?w=2000",
            specilist: "Psychiatrist",
            firstName: "Dr.shweta thakur",
            qualification: "Ph.D",
            helpline_number: "112-554-8541",
          },
];

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
